# Generated by Django 4.1.4 on 2023-01-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_myimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='car_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
