# Generated by Django 4.1.4 on 2023-01-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_myimage_car_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='myimage',
            name='serial_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='serial_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
